package feedgen

import "b2bcommerce/internal/feed"

// ChannelField is one field a destination expects in the feed. Code is the
// output column name a mapping must produce (e.g. "g:price"); Required drives
// the gap check surfaced on preview.
type ChannelField struct {
	Code     string `json:"code"`
	Label    string `json:"label"`
	Required bool   `json:"required"`
	Example  string `json:"example,omitempty"`
}

// Channel is a destination preset (Platform roadmap, Phase 4 slice 2): the
// output schema a marketplace expects, the format + XML envelope it's delivered
// in, and a starter mapping. The registry is pluggable — adding a destination is
// adding an entry, no engine change (the adapter-registry idiom).
type Channel struct {
	ID       string
	Label    string
	Format   string             // pinned delivery format; "" = the author chooses
	Fields   []ChannelField     // the destination's schema (drives presets + validation)
	Preset   feed.Mapping       // suggested starter mapping (best effort from the product source)
	Envelope *feed.XMLEnvelope  // XML document shape; nil = the generic <feed><item>
}

// googleEnvelope is Google Shopping's RSS 2.0 document with the g: namespace.
var googleEnvelope = &feed.XMLEnvelope{
	Root: "rss",
	RootAttrs: []feed.XMLAttr{
		{Name: "version", Value: "2.0"},
		{Name: "xmlns:g", Value: "http://base.google.com/ns/1.0"},
	},
	Channel: "channel",
	Item:    "item",
	Header: []feed.XMLAttr{
		{Name: "title", Value: "Product feed"},
		{Name: "link", Value: ""},
		{Name: "description", Value: "Generated by Teggo"},
	},
	Qualified: true, // keep g:id / g:price etc. under the declared namespace
}

var (
	channelOrder = []string{"custom", "google_shopping", "amazon"}
	channelByID  = map[string]Channel{
		"custom": {
			ID: "custom", Label: "Custom", Format: "", // any format, no required fields
		},
		"google_shopping": {
			ID: "google_shopping", Label: "Google Shopping", Format: "xml", Envelope: googleEnvelope,
			Fields: []ChannelField{
				{Code: "g:id", Label: "ID", Required: true, Example: "SKU-123"},
				{Code: "title", Label: "Title", Required: true},
				{Code: "description", Label: "Description", Required: true},
				{Code: "link", Label: "Product URL", Required: true, Example: "https://store.example/p/sku-123"},
				{Code: "g:image_link", Label: "Image URL", Required: true},
				{Code: "g:price", Label: "Price", Required: true, Example: "9.99 USD"},
				{Code: "g:availability", Label: "Availability", Required: true, Example: "in_stock"},
				{Code: "g:condition", Label: "Condition", Required: false, Example: "new"},
			},
			Preset: feed.Mapping{
				{Out: "g:id", Src: "sku"},
				{Out: "title", Src: "name"},
				{Out: "description", Src: "description"},
				{Out: "link", Src: "slug"},
				{Out: "g:image_link", Src: "image_url"},
				{Out: "g:availability", Const: "in_stock"},
				{Out: "g:condition", Const: "new"},
				// g:price is intentionally unmapped: the product source carries no
				// price, so the gap check flags it for the author (e.g. from attr.price).
			},
		},
		"amazon": {
			ID: "amazon", Label: "Amazon (flat file)", Format: "csv",
			Fields: []ChannelField{
				{Code: "sku", Label: "Seller SKU", Required: true},
				{Code: "item_name", Label: "Item name", Required: true},
				{Code: "product_description", Label: "Description", Required: false},
				{Code: "standard_price", Label: "Price", Required: true},
				{Code: "quantity", Label: "Quantity", Required: true},
				{Code: "main_image_url", Label: "Main image URL", Required: false},
			},
			Preset: feed.Mapping{
				{Out: "sku", Src: "sku"},
				{Out: "item_name", Src: "name"},
				{Out: "product_description", Src: "description"},
				{Out: "main_image_url", Src: "image_url"},
				// standard_price + quantity aren't in the product source → flagged.
			},
		},
	}
)

// ResolveChannel returns the channel for an id, defaulting to "custom" for an
// empty id and reporting ok=false for an unknown one.
func ResolveChannel(id string) (Channel, bool) {
	if id == "" {
		return channelByID["custom"], true
	}
	c, ok := channelByID[id]
	return c, ok
}

// AllChannels lists the registry in stable order.
func AllChannels() []Channel {
	out := make([]Channel, 0, len(channelOrder))
	for _, id := range channelOrder {
		out = append(out, channelByID[id])
	}
	return out
}

// EffectiveFormat is the channel's pinned format, or the feed's own when the
// channel doesn't pin one (custom).
func (c Channel) EffectiveFormat(feedFormat string) string {
	if c.Format != "" {
		return c.Format
	}
	return feed.NormalizeFormat(feedFormat)
}

// MissingRequired returns the required field codes the mapping does not produce
// — the gap between what the channel needs and what the feed maps.
func (c Channel) MissingRequired(m feed.Mapping) []string {
	produced := make(map[string]struct{}, len(m))
	for _, f := range m {
		if f.Out != "" {
			produced[f.Out] = struct{}{}
		}
	}
	var missing []string
	for _, fld := range c.Fields {
		if fld.Required {
			if _, ok := produced[fld.Code]; !ok {
				missing = append(missing, fld.Code)
			}
		}
	}
	return missing
}
