/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["storefrontLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["storefrontListProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storefront/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["storefrontGetProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListProducts"];
        put?: never;
        post: operations["adminCreateProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminGetProduct"];
        put: operations["adminUpdateProduct"];
        post?: never;
        delete: operations["adminDeleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminListProductCategories"];
        put?: never;
        post: operations["adminAssignProductCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListCategories"];
        put?: never;
        post: operations["adminCreateCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAttributes"];
        put?: never;
        post: operations["adminCreateAttribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/attribute-families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAttributeFamilies"];
        put?: never;
        post: operations["adminCreateAttributeFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListCustomers"];
        put?: never;
        post: operations["adminCreateCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminGetCustomer"];
        put: operations["adminUpdateCustomer"];
        post?: never;
        delete: operations["adminDeleteCustomer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers/{id}/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminCustomerHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminListCustomerUsers"];
        put?: never;
        post: operations["adminCreateCustomerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customers/{id}/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["adminListCustomerAddresses"];
        put?: never;
        post: operations["adminCreateCustomerAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/customer-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListCustomerGroups"];
        put?: never;
        post: operations["adminCreateCustomerGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** Format: int64 */
            org_id?: number;
        };
        AuthToken: {
            token: string;
        };
        /** @description Flexible product attributes keyed by attribute code. */
        Attributes: {
            [key: string]: unknown;
        };
        AdminProduct: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            public_id: string;
            sku: string;
            /** @enum {string} */
            type: "simple" | "configurable" | "kit" | "digital";
            name: string;
            slug: string;
            description?: string | null;
            /** @enum {string} */
            status: "draft" | "active" | "disabled";
            attributes?: components["schemas"]["Attributes"];
            unit: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            attribute_family_id?: number | null;
        };
        ProductInput: {
            sku: string;
            /** @enum {string} */
            type?: "simple" | "configurable" | "kit" | "digital";
            name: string;
            slug: string;
            description?: string | null;
            /** @enum {string} */
            status?: "draft" | "active" | "disabled";
            attributes?: components["schemas"]["Attributes"];
            unit?: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            attribute_family_id?: number | null;
        };
        AdminProductList: {
            items: components["schemas"]["AdminProduct"][];
            page: number;
            /** Format: int64 */
            total?: number;
        };
        StorefrontProduct: {
            /** Format: uuid */
            public_id: string;
            sku: string;
            name: string;
            slug: string;
            description?: string | null;
            status: string;
            attributes?: components["schemas"]["Attributes"];
            unit: string;
        };
        StorefrontProductList: {
            items: components["schemas"]["StorefrontProduct"][];
            page: number;
        };
        Category: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            parent_id?: number | null;
            name: string;
            slug: string;
            sort_order: number;
        };
        CategoryInput: {
            name: string;
            slug: string;
            /** Format: int64 */
            parent_id?: number | null;
            sort_order?: number;
        };
        Attribute: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id?: number;
            code: string;
            label: string;
            /** @enum {string} */
            data_type: "text" | "number" | "boolean" | "select" | "multiselect" | "date" | "file" | "price";
            options?: string[] | null;
            is_filterable?: boolean;
            is_variant_axis?: boolean;
        };
        AttributeInput: {
            code: string;
            label: string;
            /** @enum {string} */
            data_type: "text" | "number" | "boolean" | "select" | "multiselect" | "date" | "file" | "price";
            options?: string[] | null;
            is_filterable?: boolean;
            is_variant_axis?: boolean;
        };
        AttributeFamily: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id?: number;
            name: string;
        };
        ListWrapperCategory: {
            items?: components["schemas"]["Category"][];
        };
        ListWrapperAttribute: {
            items?: components["schemas"]["Attribute"][];
        };
        ListWrapperAttributeFamily: {
            items?: components["schemas"]["AttributeFamily"][];
        };
        Customer: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            public_id: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            customer_group_id?: number | null;
            name: string;
            tax_id?: string | null;
            payment_terms_days: number;
            /** @description decimal */
            credit_limit: string;
            /** Format: int64 */
            default_price_list_id?: number | null;
            /** Format: int64 */
            assigned_sales_rep_id?: number | null;
            is_active: boolean;
        };
        CustomerInput: {
            name: string;
            tax_id?: string | null;
            payment_terms_days?: number;
            credit_limit?: string;
            /** Format: int64 */
            customer_group_id?: number | null;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            assigned_sales_rep_id?: number | null;
        };
        CustomerList: {
            items: components["schemas"]["Customer"][];
            page: number;
            /** Format: int64 */
            total?: number;
        };
        CustomerHierarchy: {
            /** Format: int64 */
            customer_id?: number;
            ancestors?: {
                /** Format: int64 */
                id?: number;
                depth?: number;
            }[];
        };
        CustomerGroup: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id?: number;
            name: string;
        };
        CustomerUser: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            customer_id: number;
            email: string;
            full_name: string;
            /** @enum {string} */
            role: "buyer" | "approver" | "admin";
            spending_limit?: string | null;
            is_active: boolean;
        };
        CustomerUserInput: {
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
            /** @enum {string} */
            role?: "buyer" | "approver" | "admin";
            spending_limit?: string | null;
        };
        CustomerAddress: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            customer_id: number;
            /** @enum {string} */
            type: "billing" | "shipping";
            is_default?: boolean;
            line1: string;
            line2?: string | null;
            city: string;
            region?: string | null;
            postal_code?: string | null;
            country: string;
        };
        CustomerAddressInput: {
            /** @enum {string} */
            type: "billing" | "shipping";
            is_default?: boolean;
            line1: string;
            line2?: string | null;
            city: string;
            region?: string | null;
            postal_code?: string | null;
            country: string;
        };
        ListWrapperCustomerGroup: {
            items?: components["schemas"]["CustomerGroup"][];
        };
        ListWrapperCustomerUser: {
            items?: components["schemas"]["CustomerUser"][];
        };
        ListWrapperCustomerAddress: {
            items?: components["schemas"]["CustomerAddress"][];
        };
    };
    responses: {
        /** @description Error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    storefrontLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    storefrontListProducts: {
        parameters: {
            query?: {
                category?: string;
                q?: string;
                /** @description JSON object of attribute equalities */
                filter?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorefrontProductList"];
                };
            };
        };
    };
    storefrontGetProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorefrontProduct"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminListProducts: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductList"];
                };
            };
        };
    };
    adminCreateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    adminGetProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminUpdateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    adminDeleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminListProductCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category_ids?: number[];
                    };
                };
            };
        };
    };
    adminAssignProductCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    category_id: number;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperCategory"];
                };
            };
        };
    };
    adminCreateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    adminListAttributes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperAttribute"];
                };
            };
        };
    };
    adminCreateAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
        };
    };
    adminListAttributeFamilies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperAttributeFamily"];
                };
            };
        };
    };
    adminCreateAttributeFamily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeFamily"];
                };
            };
        };
    };
    adminListCustomers: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
        };
    };
    adminCreateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    adminGetCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminUpdateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminDeleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminCustomerHierarchy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerHierarchy"];
                };
            };
        };
    };
    adminListCustomerUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperCustomerUser"];
                };
            };
        };
    };
    adminCreateCustomerUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUserInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerUser"];
                };
            };
        };
    };
    adminListCustomerAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperCustomerAddress"];
                };
            };
        };
    };
    adminCreateCustomerAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerAddressInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerAddress"];
                };
            };
        };
    };
    adminListCustomerGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWrapperCustomerGroup"];
                };
            };
        };
    };
    adminCreateCustomerGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerGroup"];
                };
            };
        };
    };
}
